version: '3.6'
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
    - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /:/hostfs:ro
    environment:
    - HOST_ETC=/hostfs/etc
    - HOST_PROC=/hostfs/proc
    - HOST_SYS=/hostfs/sys
    - HOST_VAR=/hostfs/var
    - HOST_RUN=/hostfs/run
    - HOST_MOUNT_PREFIX=/hostfs
    depends_on:
      - influxdb
    links:
      - influxdb:influxdb
    networks:
    - influxdb-telegraf-net

  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=Ruslan
    - DOCKER_INFLUXDB_INIT_PASSWORD=PASSWORD
    - DOCKER_INFLUXDB_INIT_ORG=bell
    - DOCKER_INFLUXDB_INIT_BUCKET=linux_bucket
    - DOCKER_INFLUXDB_INIT_RETENTION=2w
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xe4Xpa1-w0uMnSFAR2Y3wqxTRJkjAvOJBrNvfLOXftOrom1Hu4K7TaxKyLV5QmNNawy2boAyGEfbmFV80L-GRg==
    - V1_DB_NAME=v1-db
    - V1_RP_NAME=v1-rp
    - V1_AUTH_USERNAME=Ruslan
    - V1_AUTH_PASSWORD=PASSWORD
    ports:
    - '8086:8086'
    volumes:
    - $PWD/data:/var/lib/influxdb2
    - $PWD/config:/etc/influxdb2
    #- $PWD/scripts:/docker-entrypoint-initdb.d
    networks:
    - influxdb-telegraf-net
networks:
  influxdb-telegraf-net:
    name: influxdb-telegraf-net
    driver: bridge
